"""Application factory."""
import logging
import os

from dotenv import load_dotenv
from flask import Flask

from chat import config
from chat.corpus import build_corpus
from chat.routes import chat_bp
from chat.schema_tool import schema_names
from chat.security import DailyBudget, RateLimiter


def create_app(overrides: dict | None = None) -> Flask:
    load_dotenv()
    logging.basicConfig(level=logging.INFO)

    app = Flask(__name__)
    overrides = overrides or {}

    state_dir = overrides.get("STATE_DIR", config.STATE_DIR)
    budget_limit = overrides.get("DAILY_BUDGET_USD", config.DAILY_BUDGET_USD)

    app.config.update(
        # Flask leaves this unset, meaning an unbounded request body. Werkzeug
        # rejects anything larger with a 413 before we parse a byte of it.
        MAX_CONTENT_LENGTH=config.MAX_REQUEST_BYTES,
        SCHEMA_DIR=overrides.get("SCHEMA_DIR", config.SCHEMA_DIR),
        ALLOWED_ORIGIN=overrides.get("ALLOWED_ORIGIN", config.ALLOWED_ORIGIN),
        RATE_LIMITER=RateLimiter(
            config.RATE_LIMIT_CALLS, config.RATE_LIMIT_WINDOW_SECONDS
        ),
        BUDGET=DailyBudget(state_dir / "budget.json", budget_limit),
    )

    # Corpus is read once, at startup. The service must be restarted after a
    # content deploy or it will keep answering from the previous build.
    app.config["CORPUS"] = overrides.get("CORPUS") or build_corpus(
        config.DOCS_DIR, config.SITE_BASE_URL
    )

    # src/data/schema/ is gitignored and regenerated by `npm run gen:schema`
    # (which runs on prebuild). On a fresh clone that has not been built, the
    # directory is empty, the tool's enum would be empty, and `strict: true`
    # against an empty enum makes the API reject every single request. Fail
    # loudly at startup instead of at the user's first question.
    if not schema_names(app.config["SCHEMA_DIR"]):
        raise RuntimeError(
            f"No schema files in {app.config['SCHEMA_DIR']}. "
            "Run `npm run gen:schema` (or `npm run build`) before starting "
            "the chat service."
        )

    # streamflows_auth.tokens.decode_token reads os.environ["JWT_SECRET"] with
    # direct indexing, so an unset value is a KeyError on EVERY request — a
    # 500 per user rather than a service that refuses to start. Fail at boot.
    if not os.environ.get("JWT_SECRET"):
        raise RuntimeError(
            "JWT_SECRET is not set, so every request would fail while "
            "verifying the session cookie. Set it in the service's "
            "EnvironmentFile to the same value the other streamflows.org "
            "apps use."
        )

    if "ANTHROPIC_CLIENT" in overrides:
        app.config["ANTHROPIC_CLIENT"] = overrides["ANTHROPIC_CLIENT"]
    else:
        import anthropic

        app.config["ANTHROPIC_CLIENT"] = anthropic.Anthropic()

    app.register_blueprint(chat_bp)
    app.logger.info("corpus loaded: %d chars", len(app.config["CORPUS"]))
    return app


app = create_app()
