<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--Delft FEWS (Copyright 2003 WL | Delft Hydraulics) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:fews="http://www.wldelft.nl/fews" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<include schemaLocation="sharedTypes.xsd"/>
	<include schemaLocation="deprecatedThresholds.xsd"/>
	<element name="thresholdGroups" type="fews:ThresholdGroupsComplexType">
		<annotation>
			<documentation>Contains definitions of threshold groups with thresholds. In this configuration file the available thresholds are defined. For a given threshold the options that are independent of location and parameter are also defined in this file. Additional threshold options for specific locations and parameters are defined in the thresholdValueSets configuration file.</documentation>
		</annotation>
	</element>
	<complexType name="ThresholdGroupsComplexType">
		<sequence>
			<element name="eventExpiryTime" type="fews:CalendarTimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional expiry time for threshold events in the ThresholdEvent table in the database.</documentation>
				</annotation>
			</element>
			<element name="maxActionEventDuration" type="fews:TimeSpanComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional maximum duration of actions (like e.g. enhanced forecasting mode). An action can be switched on by a threshold upActionLogEvent. When this duration has passed after the most recent upActionLogEvent that switched on the action, then the action is automatically switched off. If not defined, then uses duration of one day.</documentation>
				</annotation>
			</element>
			<element name="forecastAvailableThreshold" type="fews:ForecastAvailableThresholdComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional threshold that triggers forecast available threshold events. If this is specified, then forecast available events will be logged and these events can then be used in the SkillScoreDisplay. A forecast available threshold event indicates if there is a forecast available for a given observed threshold crossing event.</documentation>
				</annotation>
			</element>
			<element name="thresholdGroup" type="fews:ThresholdGroupComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>One or more threshold groups. When thresholds are used or displayed, then it is possible to select which group of thresholds should be used or displayed.</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ThresholdGroupComplexType">
		<sequence>
			<element name="defaultThreshold" type="fews:DefaultThresholdComplexType">
				<annotation>
					<documentation>Extra information for the state in which no thresholds are crossed. The state in which no thresholds are crossed always corresponds to the least severe warning level in the thresholdWarningLevels configuration file. The least severe warning level is used e.g. to get the color to display in the user interface when no thresholds are crossed.</documentation>
				</annotation>
			</element>
			<group ref="fews:ThresholdChoiceGroup">
				<annotation>
					<documentation>One or more thresholds. A threshold generates a thresholdEvent when certain conditions are met. These conditions can be different for different locations and parameters. For each threshold the conditions for specific locations and parameters are defined in the thresholdValueSets configuration file.</documentation>
				</annotation>
			</group>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this threshold group.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType">
			<annotation>
				<documentation>Name of this threshold group, e.g. "Public" or "Internal". This name is used when this threshold group is displayed. If not specified, then the id is used when this threshold group is displayed.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<group name="ThresholdChoiceGroup">
		<annotation>
			<documentation>Groups all types of thresholds.</documentation>
		</annotation>
		<sequence>
			<element name="levelThreshold" type="fews:LevelThresholdComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>A threshold that triggers a threshold event if a certain level is crossed upwards or downwards.</documentation>
				</annotation>
			</element>
			<element name="rateThreshold" type="fews:RateThresholdComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>A threshold that triggers a threshold event if the rate of change of data values becomes higher or lower than a certain rate, e.g. -0.1 m per hour.</documentation>
				</annotation>
			</element>
			<element name="maxThreshold" type="fews:MaxThresholdComplexType" minOccurs="0">
				<annotation>
					<documentation>A threshold that triggers a threshold event if there is a peak (maximum) in the data. The peak has to be higher than a certain level and has to be the maximum within a certain time window. If a maximum is at the end of a time series, then it does not count as a peak.</documentation>
				</annotation>
			</element>
		</sequence>
	</group>
	<complexType name="DefaultThresholdComplexType">
		<attribute name="shortName" type="fews:nameStringType" use="required">
			<annotation>
				<documentation>Short name for the state in which no thresholds are crossed. This short name is used e.g. for the column headers in the threshold crossing counts tables in the ThresholdOverviewDisplay.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="LevelThresholdComplexType">
		<annotation>
			<documentation>contains definition of level threshold type</documentation>
		</annotation>
		<sequence>
			<choice minOccurs="0">
				<element name="upWarningLevelId" type="fews:idStringType">
					<annotation>
						<documentation>Optional id of a warning level that will be activated for a particular location and parameter if a data value is above this threshold. Warning levels are defined in the thresholdWarningLevels configuration file. If no warningLevels are defined, then this threshold will not activate any warningLevels to be displayed, but it will still generate threshold crossing events for both upward and downward crossings.</documentation>
					</annotation>
				</element>
				<element name="downWarningLevelId" type="fews:idStringType">
					<annotation>
						<documentation>Optional id of a warning level that will be activated for a particular location and parameter if a data value is below this threshold. Warning levels are defined in the thresholdWarningLevels configuration file. If no warningLevels are defined, then this threshold will not activate any warningLevels to be displayed, but it will still generate threshold crossing events for both upward and downward crossings.</documentation>
					</annotation>
				</element>
			</choice>
			<element name="upIntId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that wil be put to the output time series if a particular threshold value of this type is crossed upwards. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
			<element name="downIntId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that wil be put to the output time series if a particular threshold value of this type is crossed downwards. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
			<element name="season" type="fews:SeasonComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional element if threshold is only valid for part of a year</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this threshold. Each threshold must have a unique id. Also thresholds that are in different threshold groups cannot have the same id.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Name of this threshold. This name is used when this threshold is displayed (e.g. in the timeSeriesDialog). If not specified, then the id is used when this threshold is displayed.</documentation>
			</annotation>
		</attribute>
		<attribute name="shortName" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Optional short name for this threshold. This short name is used e.g. for the column headers in the threshold crossing counts tables in the ThresholdOverviewDisplay. If not specified, then the id is used as short name.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="RateThresholdComplexType">
		<annotation>
			<documentation>contains definition of the rate threshold type</documentation>
		</annotation>
		<sequence>
			<element name="upIntId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that wil be put to the output time series if a particular threshold value of this type is crossed upwards. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
			<element name="downIntId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that wil be put to the output time series if a particular threshold value of this type is crossed downwards. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
			<element name="season" type="fews:SeasonComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional element if threshold is only valid for part of a year</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this threshold. Each threshold must have a unique id. Also thresholds that are in different threshold groups cannot have the same id.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Name of this threshold. This name is used when this threshold is displayed (e.g. in the timeSeriesDialog). If not specified, then the id is used when this threshold is displayed.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="MaxThresholdComplexType">
		<annotation>
			<documentation>contains definition of the max threshold type</documentation>
		</annotation>
		<sequence>
			<element name="intId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that wil be put to the output time series if a particular threshold value of this type is exceeded. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
			<element name="season" type="fews:SeasonComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional element if threshold is only valid for part of a year</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this threshold. Each threshold must have a unique id. Also thresholds that are in different threshold groups cannot have the same id.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Name of this threshold. This name is used when this threshold is displayed (e.g. in the timeSeriesDialog). If not specified, then the id is used when this threshold is displayed.</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ForecastAvailableThresholdComplexType">
		<annotation>
			<documentation>This threshold type is used to log the info that the related forecast run was available within a certain time window when the observed threshold has been crossed.</documentation>
		</annotation>
		<sequence>
			<element name="intId" type="fews:idIntType" minOccurs="0">
				<annotation>
					<documentation>DEPRECATED, do not use in new configurations. Id that will be logged as part of a ThresholdEvent in the ThresholdEvents table. This id must be unique through this file. If not specified, then this id will be generated automatically.</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="fews:idStringType" use="required">
			<annotation>
				<documentation>Identifier of this threshold. Each threshold must have a unique id. Also thresholds that are in different threshold groups cannot have the same id.</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="fews:nameStringType" use="optional">
			<annotation>
				<documentation>Name of this threshold. This name is used when this threshold is displayed (e.g. in the SkillScoreDialog). If not specified, then the id is used when this threshold is displayed.</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>
